__author__ = "Matteo Ferla. [Github](https://github.com/matteoferla)"
__email__ = "matteo.ferla@gmail.com"
__date__ = "22 March 2021 A.D."
__license__ = "MIT"
__version__ = "1.1.6"
__citation__ = "Fragmenstein paper"
